name: t1
description: "A new Flutter project."
# Prevents accidental publication to pub.dev
publish_to: 'none' # Remove this line to publish to pub.dev

# Version information
version: 1.0.0+1

# Flutter SDK version
environment:
  sdk: ^3.5.4

# Dependencies required for the project
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_auth_web: ^5.3.3
  cloud_firestore: 5.5.0 # Adjust based on compatibility

  

# Development dependencies for testing and linting
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configuration
flutter:
  uses-material-design: true
