// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT9ZVBdLS6AeamKl1ylz_LBwrcs3YYqmE',
    appId: '1:644941343907:web:4eba5f8fccbeb17413a316',
    messagingSenderId: '644941343907',
    projectId: 'messageboardapp-1d5f6',
    authDomain: 'messageboardapp-1d5f6.firebaseapp.com',
    storageBucket: 'messageboardapp-1d5f6.firebasestorage.app',
    measurementId: 'G-Y1Z692HPR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfARmDeJNyRkg_I4GMsujk9SXOts1qh6I',
    appId: '1:644941343907:android:3b6bd97b1c4d9fa513a316',
    messagingSenderId: '644941343907',
    projectId: 'messageboardapp-1d5f6',
    storageBucket: 'messageboardapp-1d5f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAkgU-7_lA6Voah2dETNniUKpHjvoCn38',
    appId: '1:644941343907:ios:a7460590004bae5613a316',
    messagingSenderId: '644941343907',
    projectId: 'messageboardapp-1d5f6',
    storageBucket: 'messageboardapp-1d5f6.firebasestorage.app',
    iosBundleId: 'com.example.t1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAkgU-7_lA6Voah2dETNniUKpHjvoCn38',
    appId: '1:644941343907:ios:a7460590004bae5613a316',
    messagingSenderId: '644941343907',
    projectId: 'messageboardapp-1d5f6',
    storageBucket: 'messageboardapp-1d5f6.firebasestorage.app',
    iosBundleId: 'com.example.t1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT9ZVBdLS6AeamKl1ylz_LBwrcs3YYqmE',
    appId: '1:644941343907:web:910d3df4a4bca91213a316',
    messagingSenderId: '644941343907',
    projectId: 'messageboardapp-1d5f6',
    authDomain: 'messageboardapp-1d5f6.firebaseapp.com',
    storageBucket: 'messageboardapp-1d5f6.firebasestorage.app',
    measurementId: 'G-MNQRPW6EVS',
  );
}
